// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Drivetrain extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private WPI_TalonFX frontLeft;
private WPI_TalonFX backLeft;
private MotorControllerGroup left;
private WPI_TalonFX frontRight;
private WPI_TalonFX backRight;
private MotorControllerGroup right;
private DifferentialDrive differentialDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Drivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
frontLeft = new WPI_TalonFX(2);
 addChild("frontLeft",frontLeft);
 frontLeft.setInverted(true);

backLeft = new WPI_TalonFX(1);
 addChild("backLeft",backLeft);
 backLeft.setInverted(true);

left = new MotorControllerGroup(frontLeft, backLeft  );
 addChild("Left",left);
 

frontRight = new WPI_TalonFX(4);
 addChild("frontRight",frontRight);
 frontRight.setInverted(false);

backRight = new WPI_TalonFX(3);
 addChild("backRight",backRight);
 backRight.setInverted(false);

right = new MotorControllerGroup(frontRight, backRight  );
 addChild("Right",right);
 

differentialDrive = new DifferentialDrive(left, right);
 addChild("Differential Drive",differentialDrive);
 differentialDrive.setSafetyEnabled(true);
differentialDrive.setExpiration(0.1);
differentialDrive.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void drive(double left, double right){
        differentialDrive.tankDrive(left, right);
    }

    public void driveAuto(){
        differentialDrive.tankDrive(0.5, 0.5);
    }

    public void leftAuto(){
        differentialDrive.tankDrive(-0.5, 0.5);
    }

    public void rightAuto(){
        differentialDrive.tankDrive(0.5, -0.5);
    }

    public void stop(){
        differentialDrive.tankDrive(0, 0);
    }
}


